"""
Builds DataChallenge_Team <NUMBER>_Report.pdf from the content below, formatted to the
CDU IT Code Fair 2026 Data Innovation Challenge report spec:
  A4, continuous page numbering, header+footer with Team Number + Page Number,
  Title 20pt bold / headings 14pt bold / body 11pt / captions+references 10pt,
  <=8 body pages (excl. title/references/appendices), Calibri-or-Arial.
Font note: Calibri isn't a base PDF font and Arial isn't bundled with reportlab either;
this uses Helvetica, which is metrically identical to Arial (the standard substitute) —
swap in embedded TrueType Calibri/Arial if you want the literal font family.

Every number in the text below was computed directly from data/processed/*.csv by the
coordinator session (see chat) and cross-checked against docs/PROJECT_CONTEXT.md,
docs/SERVICES_LAYER.md and docs/CODE_ANALYSIS.md. Charts are regenerated by
make_charts.py from the same files, so text and figures can't drift apart — re-run
make_charts.py first if data/processed/ changes.

Run:  py -3 report/make_charts.py && py -3 report/build_report.py
"""
from pathlib import Path

from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle
from reportlab.lib.units import cm
from reportlab.lib.enums import TA_CENTER, TA_JUSTIFY
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, Image, PageBreak, KeepTogether,
)

# ============================================================================
# FILL THESE IN before the final submission — everything else is generated.
# ============================================================================
TEAM_NUMBER = "XX"          # <-- competition-assigned team number, e.g. "07"
TEAM_NAME = "Team ASTRA"    # matches GROUP_NAME in app/app.py
TEAM_MEMBERS = [            # (name, role) — replace with the real roster
    ("[Member name]", "[Role, e.g. Data pipeline / Dashboard / Report]"),
    ("[Member name]", "[Role]"),
    ("[Member name]", "[Role]"),
]
REPORT_DATE = "29 September 2026"
REPO_URL = "[repo URL — GitHub link or note 'source code included in submission ZIP']"
# ============================================================================

ROOT = Path(__file__).resolve().parent.parent
ASSETS = Path(__file__).resolve().parent / "assets"
OUT = Path(__file__).resolve().parent / "out" / f"DataChallenge_Team {TEAM_NUMBER}_Report.pdf"

PAGE_W, PAGE_H = A4
MARGIN = 2.2 * cm

# ---------------------------------------------------------------------------
# Styles (Title 20pt bold / headings 14pt bold / body 11pt / captions+refs 10pt)
# ---------------------------------------------------------------------------
FONT = "Helvetica"
FONT_B = "Helvetica-Bold"

styles = {
    "TitlePage": ParagraphStyle("TitlePage", fontName=FONT_B, fontSize=20, leading=25,
                                 alignment=TA_CENTER, spaceAfter=14),
    "SubTitle": ParagraphStyle("SubTitle", fontName=FONT, fontSize=13, leading=17,
                                alignment=TA_CENTER, spaceAfter=8, textColor=colors.HexColor("#333333")),
    "TitleMeta": ParagraphStyle("TitleMeta", fontName=FONT, fontSize=11, leading=16,
                                 alignment=TA_CENTER, spaceAfter=4),
    "H1": ParagraphStyle("H1", fontName=FONT_B, fontSize=14, leading=18, spaceBefore=14, spaceAfter=8,
                          textColor=colors.HexColor("#111111")),
    "H2": ParagraphStyle("H2", fontName=FONT_B, fontSize=12, leading=14.5, spaceBefore=8, spaceAfter=4,
                          textColor=colors.HexColor("#222222")),
    "Body": ParagraphStyle("Body", fontName=FONT, fontSize=11, leading=14.2, spaceAfter=6,
                            alignment=TA_JUSTIFY),
    "BodyBold": ParagraphStyle("BodyBold", fontName=FONT_B, fontSize=11, leading=14.2, spaceAfter=6),
    "Bullet": ParagraphStyle("Bullet", fontName=FONT, fontSize=11, leading=14, spaceAfter=3,
                              leftIndent=14, bulletIndent=2, alignment=TA_JUSTIFY),
    "Caption": ParagraphStyle("Caption", fontName=FONT, fontSize=10, leading=13, spaceAfter=10,
                               alignment=TA_CENTER, textColor=colors.HexColor("#444444")),
    "Ref": ParagraphStyle("Ref", fontName=FONT, fontSize=10, leading=14, spaceAfter=6,
                           leftIndent=14, firstLineIndent=-14),
    "Summary": ParagraphStyle("Summary", fontName=FONT, fontSize=11, leading=16, spaceAfter=8,
                               alignment=TA_JUSTIFY, borderPadding=0),
}


def P(text, style="Body"):
    return Paragraph(text, styles[style])


def bullets(items, style="Bullet"):
    return [Paragraph(f"&bull;&nbsp;&nbsp;{t}", styles[style]) for t in items]


# ---------------------------------------------------------------------------
# Header / footer — every page except the title page. "Team Number" and
# "Page Number" both appear in both, per the format spec.
# ---------------------------------------------------------------------------
def header_footer(canvas, doc):
    if doc.page == 1:
        return  # title page carries no running header/footer
    canvas.saveState()
    page_no = doc.page - 1  # continuous numbering starting at 1 on the Summary page
    canvas.setFont(FONT, 9)
    canvas.setFillColor(colors.HexColor("#555555"))
    # Header
    canvas.drawString(MARGIN, PAGE_H - MARGIN + 10, f"{TEAM_NAME} — {TEAM_NUMBER}")
    canvas.drawRightString(PAGE_W - MARGIN, PAGE_H - MARGIN + 10, f"Page {page_no}")
    canvas.line(MARGIN, PAGE_H - MARGIN + 4, PAGE_W - MARGIN, PAGE_H - MARGIN + 4)
    # Footer
    canvas.line(MARGIN, MARGIN - 10, PAGE_W - MARGIN, MARGIN - 10)
    canvas.drawString(MARGIN, MARGIN - 22, f"Team {TEAM_NUMBER} — NT Deadzone Explorer, CDU IT Code Fair 2026")
    canvas.drawRightString(PAGE_W - MARGIN, MARGIN - 22, f"Page {page_no}")
    canvas.restoreState()


def fig(name, width=15.5 * cm):
    img = Image(str(ASSETS / name))
    ratio = img.imageHeight / img.imageWidth
    img.drawWidth = width
    img.drawHeight = width * ratio
    return img


def data_table(rows, col_widths, header=True):
    t = Table(rows, colWidths=col_widths)
    style = [
        ("FONT", (0, 0), (-1, -1), FONT, 9.5),
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ("GRID", (0, 0), (-1, -1), 0.4, colors.HexColor("#BBBBBB")),
        ("TOPPADDING", (0, 0), (-1, -1), 4),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
        ("LEFTPADDING", (0, 0), (-1, -1), 6),
    ]
    if header:
        style += [
            ("FONT", (0, 0), (-1, 0), FONT_B, 9.5),
            ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#EFEFEF")),
        ]
    t.setStyle(TableStyle(style))
    return t


# ============================================================================
# CONTENT
# ============================================================================
story = []

# ---- Title page -------------------------------------------------------------
story.append(Spacer(1, 4.5 * cm))
story.append(P("Same Bars, No Backup: Quantifying and Targeting\nRemote Connectivity Risk in the Northern Territory", "TitlePage"))
story.append(P("NT Deadzone Explorer — a reproducible data pipeline and interactive prototype for the "
               "CDU IT Code Fair 2026 Data Innovation Challenge (Theme: Remote Connectivity)", "SubTitle"))
story.append(Spacer(1, 1.2 * cm))
story.append(P(f"Team Number: {TEAM_NUMBER}", "TitleMeta"))
story.append(P(f"Team Name: {TEAM_NAME}", "TitleMeta"))
for name, role in TEAM_MEMBERS:
    story.append(P(f"{name} — {role}", "TitleMeta"))
story.append(Spacer(1, 0.6 * cm))
story.append(P(REPORT_DATE, "TitleMeta"))
story.append(P("CDU IT Code Fair 2026 — Data Innovation Challenge", "TitleMeta"))
story.append(PageBreak())

# ---- Summary ------------------------------------------------------------
story.append(P("Summary", "H1"))
story.append(P(
    "Nearly three in four people living in the Northern Territory's officially recognised remote "
    "communities depend on mobile infrastructure that has no backup if it fails. We built a "
    "reproducible pipeline that joins nine public datasets — BushTel's 792-community register, the "
    "2021 Census, the ACMA radiocommunications licence register, NBN footprints, the Mobile Black "
    "Spot Program (MBSP), the NT mobile coverage guide, RICT, and school/medical/emergency-facility "
    "extracts — into one village-level table, and an interactive dashboard (\"NT Deadzone Explorer\") "
    "that turns it into a filterable map, table, and site-selection tool. We tested three hypotheses: "
    "that nominal coverage overstates real resilience, that current infrastructure investment is not "
    "targeted by population impact, and that connectivity gaps compound with service gaps rather than "
    "occurring independently. All three are supported by the data. 75% of communities within reach of "
    "a tower have no second network as backup; the 8 mobile-black-spot sites still awaiting "
    "construction would reach only 11% of the at-risk population within macro-cell range, versus 44% "
    "reachable by the same number of sites chosen with a simple population-weighted method; and 98% of "
    "communities beyond the mobile coverage threshold also have no school, medical facility, or "
    "emergency service within 10 km. We present these findings with explicit ethical and cultural "
    "caveats — this analysis is decision support, not a decision, and does not substitute for "
    "community consultation — and close with recommendations for government, industry and community "
    "stakeholders.", "Summary"))

# ---- Introduction -------------------------------------------------------
story.append(P("Introduction", "H1"))
story.append(P(
    "The Northern Territory's remote and very remote communities are routinely described as "
    "\"covered\" or \"not covered\" by mobile network, as if connectivity were binary. That framing "
    "hides two things that matter more in practice: whether coverage, where it exists, is resilient "
    "to a single fault; and whether a connectivity gap is the only gap a community is carrying, or "
    "one of several. This report asks a more specific question than \"where is the coverage "
    "gap\": <b>is nominal coverage a reliable proxy for real resilience, is current infrastructure "
    "investment reaching the people who need it most, and does a mobile-coverage gap predict other "
    "kinds of disadvantage?</b>", "Body"))
story.append(P(
    "We frame this as three testable hypotheses, built directly from linking three data layers for "
    "all 792 NT communities listed in the BushTel Community Profile and the 649 Statistical Areas "
    "Level 1 (SA1s — the Australian Bureau of Statistics' finest geography with a published "
    "population) that contain them:", "Body"))
for para in bullets([
    "<b>H1 — Fragility:</b> most NT communities within reach of mobile coverage rely on a single "
    "carrier network with no independent backup, so nominal “coverage” overstates "
    "resilience to a network-level fault.",
    "<b>H2 — Misallocation:</b> current public investment in new mobile infrastructure (the Mobile "
    "Black Spot Program, MBSP) is not targeted by population impact, and a simple, reproducible "
    "population-weighted method would reach meaningfully more people for the same number of sites.",
    "<b>H3 — Compounding vulnerability:</b> communities with the worst mobile connectivity are not "
    "randomly distributed with respect to other essential services — they are also "
    "disproportionately far from schools, health care, and emergency response.",
]):
    story.append(para)
story.append(P(
    "The purpose is to move past \"which places lack coverage\" — a question the existing NT "
    "Mobile Coverage guide already answers at a surface level — toward quantifying who is "
    "affected, how severely, and where public and industry investment has the most leverage. Scope "
    "is the Territory's 792 BushTel-listed communities (779 Remote/Very Remote, 13 Outer Regional "
    "near Darwin), using 2021 Census figures, the ACMA licence register, BushTel's own records, and "
    "— for H3 — school, health and emergency-service location data.", "Body"))
story.append(P(
    "Why SA1, not the individual village, carries the population numbers: the Census only publishes "
    "reliable population, income and household-size figures at SA1 level — the smallest "
    "geography ABS releases without breaching privacy-suppression rules. A single remote SA1 can be "
    "enormous (the Tanami SA1 spans over 140,000 km² and contains 15 named communities but a "
    "population in the hundreds), so population is a property of the region, not the individual "
    "settlement. BushTel supplies where people live and how many distinct places; the Census/SA1 "
    "layer supplies how many people and how well-off they are; the ACMA tower register supplies what "
    "connectivity infrastructure physically exists inside that same footprint. Every finding below is "
    "built on that same three-way join, never on the presence of a single dataset alone.", "Body"))

# ---- Methodology ----------------------------------------------------------
story.append(P("Methodology", "H1"))
story.append(P("Data sources and pipeline", "H2"))
story.append(P(
    "Nine public datasets are joined through an 11-step, numbered Jupyter notebook pipeline "
    "(<font face=\"Helvetica-Oblique\">notebooks/00a–11</font>, orchestrated by "
    "<font face=\"Helvetica-Oblique\">run_pipeline.py</font> so the whole table rebuilds identically "
    "from raw inputs on any machine): the BushTel Community Profile (792 communities), the 2021 "
    "Census GCP (SA1-level population, income, household size), the ABS ASGS SA1 boundary and "
    "Remoteness Area files, the ACMA Register of Radiocommunications Licences (site, licence, client "
    "and device tables — filtered to carrier transmitters in a handset frequency band and "
    "co-location-clustered within 100 m to produce 431 distinct towers from 3,771 NT-registered "
    "sites), NBN fixed-line/fixed-wireless footprints, the Mobile Black Spot Program's 49 NT funded "
    "sites, the NT Government's own mobile coverage guide, the Remote Indigenous Communications "
    "(RICT) community list, and Geoscience Australia / NT Department of Education extracts for "
    "medical, emergency and school facilities. Every source, licence and retrieval date is recorded "
    "in <font face=\"Helvetica-Oblique\">data/README.md</font>; every notebook's exact reads, joins "
    "and outputs are independently audited in "
    "<font face=\"Helvetica-Oblique\">docs/data_use_check.md</font> and "
    "<font face=\"Helvetica-Oblique\">docs/CODE_ANALYSIS.md</font>.", "Body"))
story.append(P("Distance and classification method", "H2"))
story.append(P(
    "Tower, MBSP and NBN distances are computed after projecting to EPSG:3577 (Australian Albers, an "
    "equal-area metric CRS); service-site distances use great-circle (haversine) distance on WGS84, "
    "documented as marginally less precise but adequate for triage. Every distance in this report is "
    "straight-line — a triage signal, not a drive-time or signal-strength guarantee; the NT "
    "coverage guide itself carries the same caveat (\"varies according to local conditions, "
    "especially topography and vegetation\"). Each of the 792 communities is assigned one of four "
    "resilience tiers, applied identically in the data pipeline and the dashboard: <i>beyond gap "
    "threshold</i> (no tower within 15 km and no coverage-guide claim of service), <i>single point of "
    "failure</i> (a tower exists within 15 km but none within a 10 km buffer, so a single-site fault "
    "removes coverage entirely), <i>single network only</i> (towers within reach but only one carrier "
    "network among them), and <i>multiple networks</i> (2 or more independent networks within 10 km).", "Body"))
story.append(P("The interactive prototype", "H2"))
story.append(P(
    "“NT Deadzone Explorer” (a Streamlit app, <font face=\"Helvetica-Oblique\">app/app.py</font>) "
    "reads the pipeline's output directly — it keeps no data of its own — and exposes it as a "
    "filterable map, sortable table, insight charts, and a live <b>Recommendations</b> tool. That tool "
    "implements the same population-weighted <b>greedy maximum-coverage</b> algorithm used to produce "
    "the H2 finding below: repeatedly choosing the candidate site that reaches the most not-yet-reached "
    "population, which is provably within (1 − 1/e) ≈ 63% of the best possible answer for this "
    "objective (Nemhauser, Wolsey & Fisher, 1978), benchmarked in-app against a population-weighted "
    "k-means baseline. Anyone — a planner, a community member, a judge — can choose a target "
    "population, a service radius, and a number of sites, and see the trade-off live, rather than "
    "taking our H2 finding on faith.", "Body"))
story.append(P("Statistical validation", "H2"))
story.append(P(
    "Each hypothesis was additionally tested with a formal statistical procedure, not just descriptive "
    "percentages: two one-sided exact binomial tests plus a chi-square test of independence for H1; a "
    "10,000-draw Monte Carlo permutation test for H2 (there is no closed-form sampling distribution for "
    "“population reached by k randomly chosen sites under a spatial union-coverage function”, so "
    "we built one empirically); and a Mann-Whitney U test per service type plus a Fisher's exact test for "
    "H3. Every test, fully documented and reproducible from <font face=\"Helvetica-Oblique\">"
    "data/processed/*.csv</font> with no hand-typed numbers, is in "
    "<font face=\"Helvetica-Oblique\">hypothesis_proof_notebooks/</font>; the greedy algorithm's "
    "underlying math — the submodularity argument behind its (1 − 1/e) guarantee, and a "
    "hand-checkable 6-site worked example — is in that folder's "
    "<font face=\"Helvetica-Oblique\">greedy_algorithm_explained.txt</font>.", "Body"))

# ---- Findings ---------------------------------------------------------------
story.append(P("Findings", "H1"))

story.append(P("H1 — Fragility: nominal coverage overstates resilience (supported)", "H2"))
story.append(fig("fig1_tiers.png"))
story.append(P("Figure 1. Resilience tier of all 792 NT communities, from the pipeline's tower and "
               "network-count join.", "Caption"))
story.append(P(
    "384 of 792 communities (48%) sit beyond the 15 km gap threshold entirely. Of the remaining 408 "
    "that are within reach of at least one tower, 307 (75%) have no real backup: 86 have exactly one "
    "tower reachable at all and it sits outside a practical 10 km buffer (a textbook single point of "
    "failure), and 221 have multiple towers nearby but every one of them is run by the same carrier. "
    "Only 101 communities — 13% of the Territory's total — have two or more independent "
    "networks within 10 km. This is confirmed independently at the infrastructure level: of the 431 "
    "distinct towers themselves, 331 (77%) carry only one carrier's equipment, and 325 (75%) carry "
    "Telstra specifically — meaning a single carrier's outage, not only a natural disaster, could "
    "plausibly take an entire region offline. In population terms: of the 50,889 people living in the "
    "179 SA1s that contain a BushTel community, 36,973 (73%) live in an SA1 classified fragile "
    "(beyond-threshold, single-point-of-failure, or single-network). Both proportions are tested "
    "directly against a 50% null with a one-sided exact binomial test (village-level "
    "p = 1.5×10⁻²⁵; tower-level p = 2.9×10⁻³⁰) "
    "— and fragility is not evenly spread: a chi-square test shows the fragile rate rising sharply "
    "with remoteness — 8% in Outer Regional (greater Darwin), 47% in Remote, 86% in Very Remote "
    "(χ² = 85.3, p = 3.0×10⁻¹⁹) — concentrating the "
    "risk exactly where it is hardest to reach.", "Body"))

story.append(P("H2 — Misallocation: the current investment backlog is not population-targeted (supported, with caveats)", "H2"))
story.append(fig("fig3_targeting.png"))
story.append(P("Figure 3. Population reached by the same number of new sites (8), chosen two different "
               "ways, at two candidate radii.", "Caption"))
story.append(P(
    "Of the Mobile Black Spot Program's 49 funded NT sites, 41 are built and 8 remain unbuilt; the "
    "unbuilt sites sit a median 219 km from the nearest BushTel community, more than double the "
    "already-built sites' median of 102 km. We tested directly whether that backlog is where the "
    "population need is: among the 691 “fragile” communities (beyond-threshold, "
    "single-point-of-failure or single-network), the 8 still-unbuilt MBSP sites would reach only 3,925 "
    "people — 11% of the 36,973-person fragile population — within a 40 km macro-cell range "
    "(2.3% within the project's own 15 km gap threshold). Choosing 8 sites from the same candidate "
    "pool with a population-weighted greedy algorithm instead reaches 16,251 people, 44% — almost "
    "four times the population, for an identical number of sites. A Monte Carlo permutation test makes "
    "this precise: across 10,000 random 8-site draws from the same candidate pool, MBSP's unbuilt sites "
    "reach less population than the median random draw would (42nd percentile at 40 km, 32nd percentile "
    "at 15 km) — the current backlog performs no better than chance, and if anything slightly worse. "
    "The greedy selection, by contrast, beats essentially all 10,000 random draws at both radii, "
    "consistent with its theoretical worst-case guarantee. This is not evidence that MBSP site "
    "selection was wrong: feasibility, land tenure, backhaul availability, staged funding rounds and, "
    "critically, community consultation are real constraints this model doesn't see. It is evidence "
    "that a reproducible, population-weighted method surfaces meaningfully different priorities than "
    "the current backlog, and is worth using as one input into future rounds — which is exactly "
    "what the dashboard's Recommendations tool is built to let a planner explore.", "Body"))

story.append(P("H3 — Compounding vulnerability: connectivity gaps and service gaps overlap heavily (strongly supported)", "H2"))
story.append(fig("fig2_services_gap.png"))
story.append(P("Figure 2. Median distance to the nearest school, medical facility and emergency service, "
               "compared for communities inside vs. beyond the mobile-coverage gap threshold.", "Caption"))
story.append(P(
    "Communities beyond the mobile-coverage gap threshold are 4–5 times further from every "
    "service type we measured than communities within it: a median 39.2 km to the nearest school "
    "(vs. 7.4 km), 46.2 km to the nearest medical facility (vs. 10.2 km), and 47.7 km to the nearest "
    "emergency service (vs. 12.2 km). The overlap is close to total, not partial: of the 384 "
    "communities beyond the mobile gap threshold, 375 (98%) have <i>none</i> of the three service "
    "types — no school, no medical facility, no emergency service — within 10 km, versus an "
    "overall rate across all 792 communities of only 20% having all three nearby. A mobile-coverage "
    "gap in the NT is very rarely an isolated problem: it is the visible edge of a much wider "
    "service desert. Every difference above is statistically significant (Mann-Whitney U test per "
    "service type, p &lt; 1×10⁻⁵⁴ in all three; large effect sizes, "
    "rank-biserial r = −0.64 to −0.71) and the zero-services overlap is not chance "
    "either (Fisher's exact test, odds ratio = 66, p = 5×10⁻⁸²).", "Body"))

# ---- Discussion ---------------------------------------------------------------
story.append(P("Discussion — Ethical, cultural and community impacts", "H1"))
story.append(P(
    "This dataset describes, at fine geographic resolution, which remote Aboriginal and Torres Strait "
    "Islander communities in the NT are most exposed and least resourced. That carries real risk of "
    "deficit framing — presenting communities only through what they lack — and real "
    "sensitivity around Indigenous Cultural and Intellectual Property (ICIP). We made several "
    "deliberate choices in response. First, we dropped Indigenous population share as an analysis "
    "variable, keeping a whole-community view rather than isolating ethnicity as a special or "
    "“othered” category; every finding above applies to a community as a whole, not to a "
    "demographic subgroup within it. Second, the dashboard's cultural theme uses Aboriginal-flag "
    "colours only as an accent, and shows flag imagery or community artwork only from official, "
    "unaltered files supplied with their own attribution — nothing is AI-generated or drawn in "
    "“Aboriginal style,” because traditional designs belong to specific peoples and Country "
    "and are used only with permission. An Acknowledgement of Country is built into the interface, "
    "not treated as a footnote.", "Body"))
story.append(P(
    "Second, every distance in this analysis is straight-line triage, not a coverage or drive-time "
    "guarantee — stated in-app and in every underlying notebook. Used carelessly, a triage number "
    "could be cited to justify declining or deferring investment in a community that appears "
    "“reached” on paper but is not, in the lived experience of the people there. We present "
    "the Recommendations tool explicitly as decision <i>support</i>: the greedy algorithm optimises "
    "population reached per site, and nothing else — it cannot see land tenure, community "
    "preference, cultural sites, or local infrastructure feasibility, all of which properly belong to "
    "the communities and agencies who hold that knowledge. It is offered as one input for a planning "
    "conversation, not a replacement for it.", "Body"))
story.append(P(
    "Third, the underlying data carries its own governance obligations we have respected rather than "
    "worked around: 2021 Census figures are ABS-suppressed below a small-count threshold, and this "
    "pipeline preserves that suppression (flagging <font face=\"Helvetica-Oblique\">census_pop_suppressed</font> "
    "rather than estimating a number ABS chose not to publish); the ACMA licence register carries its "
    "own usage terms (not CC-BY) that we have observed; and several data-quality issues in the source "
    "extracts — mislabelled agencies, postcodes that lose a leading zero, a facility recorded "
    "under the wrong town — were corrected transparently in the pipeline rather than silently, "
    "with every fix documented in code and in <font face=\"Helvetica-Oblique\">docs/CODE_ANALYSIS.md</font>.", "Body"))

# ---- Recommendations ------------------------------------------------------
story.append(P("Recommendations", "H1"))
story.append(P("For government", "H2"))
for p in bullets([
    "Use a reproducible, population-weighted prioritisation method — such as the greedy "
    "max-coverage tool in the dashboard — as one explicit input into future MBSP and equivalent "
    "funding rounds, alongside (not instead of) the feasibility and community-consultation criteria "
    "already in use.",
    "Fund network-redundancy grants at existing single-network sites, not only new towers: 221 "
    "communities already have tower infrastructure and would gain real resilience from a second "
    "carrier at an existing site — likely cheaper, per person protected, than an all-new build in "
    "an unserved area.",
    "Treat the 98% overlap between mobile-coverage gaps and service deserts (H3) as a signal to "
    "co-locate future investment — a new tower and a visiting health or education service reaching "
    "the same community compounds impact rather than solving one problem twice.",
]):
    story.append(p)
story.append(P("For industry", "H2"))
for p in bullets([
    "Explore infrastructure co-location / network sharing at the 221 single-network sites identified "
    "here, similar to the voluntary co-location this project already detects at 30 existing tower "
    "clusters — a lower-capital path to redundancy than new-site builds.",
    "Publish site-level network presence (which carriers actually operate at a site, not just licence "
    "records) in a form communities and planners can verify against lived experience, closing the kind "
    "of guide-vs-register discrepancy this project had to reconcile by hand.",
]):
    story.append(p)
story.append(P("For community stakeholders", "H2"))
for p in bullets([
    "Formalise the feedback loop the NT coverage guide already implies (it is explicitly "
    "“GUIDE only”) — community-reported coverage experience surfaced real discrepancies "
    "against the formal ACMA register in this analysis and is a cheap, high-value data source.",
    "Treat any connectivity-gap or service-gap ranking, including ours, as a starting point for a "
    "conversation with the affected community about priority and sequencing, not as a finished "
    "verdict — consistent with the ethical framing in the Discussion above.",
]):
    story.append(p)
story.append(P("Limitations and future work", "H2"))
story.append(P(
    "The dashboard currently requires a running Streamlit server and internet-hosted map tiles "
    "(OpenStreetMap) and fonts; every dataset it displays is local, so the remaining step toward "
    "genuine offline-first operation — one of the challenge's suggested angles — is bundling "
    "a local basemap. Services distances use haversine rather than the projected-CRS method used for "
    "towers; school coordinates are locality-level, not street-level, because the source list carries "
    "no coordinates of its own. We deliberately did not combine the connectivity-gap and services-gap "
    "flags into one score: which matters more, and how to weight them, is a policy judgement for "
    "government and community stakeholders, not something this analysis should decide silently.", "Body"))
story.append(PageBreak())

# ---- References -------------------------------------------------------------
story.append(P("References", "H1"))
refs = [
    "Australian Bureau of Statistics (2021). <i>2021 Census General Community Profile DataPack, "
    "Northern Territory</i>. https://www.abs.gov.au/census/find-census-data/datapacks",
    "Australian Bureau of Statistics (2021). <i>Australian Statistical Geography Standard (ASGS) "
    "Edition 3 — SA1 and Remoteness Area boundaries</i>. https://www.abs.gov.au/statistics/standards/"
    "australian-statistical-geography-standard-asgs/edition-3-july-2021-june-2026",
    "Australian Communications and Media Authority (ACMA). <i>Register of Radiocommunications "
    "Licences</i>, daily extract. https://www.acma.gov.au/radiocomms-licence-data",
    "Department of Infrastructure, Transport, Regional Development, Communications and the Arts. "
    "<i>Mobile Black Spot Program — funded base stations</i>. https://www.infrastructure.gov.au/"
    "media-communications-arts/phone/mobile-services-and-coverage/mobile-black-spot-program",
    "National Indigenous Australians Agency (2024). <i>Remote Indigenous Communications (RICT) "
    "community list</i>.",
    "Northern Territory Government — Chief Minister and Cabinet. <i>BushTel Community "
    "Profile 2024</i>. https://bushtel.nt.gov.au/",
    "Northern Territory Open Data Portal. <i>Remote Communities with 3G/4G Mobile Coverage</i> and "
    "<i>Remote Sites with Mobile Phone Small Cell Coverage</i>. https://data.nt.gov.au/",
    "nbn co (2024). <i>National Broadband Network fixed-line and fixed-wireless technology "
    "footprints</i>, via data.gov.au.",
    "Geoscience Australia / National Health Services Directory. <i>Medical and emergency facility "
    "extracts, Northern Territory</i>.",
    "Northern Territory Department of Education. <i>NT School List (public)</i>.",
    "Nemhauser, G. L., Wolsey, L. A., & Fisher, M. L. (1978). An analysis of approximations for "
    "maximizing submodular set functions — I. <i>Mathematical Programming</i>, 14(1), 265–294.",
    "Charles Darwin University (2026). <i>IT Code Fair 2026 — Data Innovation Challenge "
    "brief</i>. https://itcodefair.cdu.edu.au/data-innovation-challenge/",
]
for r in refs:
    story.append(P(r, "Ref"))
story.append(P(
    "Full source, licence and retrieval-date detail for every dataset above is in "
    "<font face=\"Helvetica-Oblique\">data/README.md</font> in the submitted source code.", "Body"))
story.append(PageBreak())

# ---- Appendices ---------------------------------------------------------------
story.append(P("Appendices", "H1"))
story.append(P("Appendix A — AI-use declaration", "H2"))
story.append(P(
    "<i>[Team to review and finalise before submission — draft below reflects the AI assistance "
    "actually used in this session; edit to match your own use.]</i> Generative AI (Claude, via "
    "Claude Code) was used to assist with: (1) auditing and documenting the existing data pipeline and "
    "codebase, (2) computing and cross-checking the statistics cited in the Findings section directly "
    "against the processed data files, (3) drafting the narrative framing, hypothesis structure and "
    "prose of this report, and (4) generating the report's layout and charts via a Python script. All "
    "cited figures were computed from <font face=\"Helvetica-Oblique\">data/processed/*.csv</font> and "
    "are independently reproducible by re-running <font face=\"Helvetica-Oblique\">report/make_charts.py</font> "
    "and the code in this appendix's source. Team members reviewed, verified and take responsibility "
    "for all claims, figures and recommendations in this report.", "Body"))
story.append(P("Appendix B — Source code", "H2"))
story.append(P(
    f"Full source code, the reproducing README, this report's generation script, and the formal "
    f"hypothesis-test notebooks are included in the submission ZIP under the project root. Repository: "
    f"{REPO_URL}. Rebuild the full analysis with "
    f"<font face=\"Helvetica-Oblique\">python run_pipeline.py</font>; run the dashboard with "
    f"<font face=\"Helvetica-Oblique\">streamlit run app/app.py</font>; rebuild this report with "
    f"<font face=\"Helvetica-Oblique\">py -3 report/make_charts.py && py -3 report/build_report.py</font>; "
    f"the three hypothesis tests (H1/H2/H3) and the greedy-algorithm explainer are in "
    f"<font face=\"Helvetica-Oblique\">hypothesis_proof_notebooks/</font>.", "Body"))
story.append(P("Appendix C — Dataset links", "H2"))
story.append(P(
    "See References above and <font face=\"Helvetica-Oblique\">data/README.md</font> for the full "
    "list with licences and retrieval dates.", "Body"))

# ---------------------------------------------------------------------------
doc = SimpleDocTemplate(
    str(OUT), pagesize=A4,
    leftMargin=MARGIN, rightMargin=MARGIN, topMargin=MARGIN + 6, bottomMargin=MARGIN + 6,
    title="NT Deadzone Explorer — Data Innovation Challenge Report", author=TEAM_NAME,
)
doc.build(story, onFirstPage=header_footer, onLaterPages=header_footer)
print("wrote", OUT, f"({OUT.stat().st_size / 1024:.0f} KB)")
